### ISSUE TITLE
HDMI port is not working, any idea?

### ISSUE THREAD

**Issue by VGEAREN** [mendax1234/ThinkpadX390-Opencore-EFI#16]
When I plug in the hdmi port, the monitor is still black and the mouse starts stuttering.
But the expander work.

**Comment by mendax1234** [comment]
Do you use macOS Monterey or ventura? l guess that because the USBinjectall.kext isn't supported since macOS Monterey, so the hdmi port will also be affected. Besides, the internal camera is also affected. And can your internal camera be used on Monterey?

What's more, l notice that you also use PCbeta, and can you provide me with an invitation code in PCbeta? Thanks!

Best
Daniel

**Comment by VGEAREN** [comment]
I didn't find any way to share the invitation code, any idea?

**Comment by mendax1234** [comment]
> I didn't find any way to share the invitation code, any idea?

Perhaps you can ask PCBeta's administrator, l remember that you can buy an invitation code. Thanks!
